### ISSUE TITLE
[Bug] Image stored is inverted

### ISSUE THREAD

**Issue by leedave** [CodyTolene/Flipper-Zero-Camera-Suite#23]
Hi There

Nice project, just managed to get an ESL32 cam and set it up to work with your app. 

I did notice the images saved as bitmap are always in inverted B/W.

**Comment by CodyTolene** [comment]
I did not notice, good catch! I will have to test this and get a fix in. Marking as a bug. Thank you

**Comment by CodyTolene** [comment]
@leedave Resolved [here](https://github.com/CodyTolene/Flipper-Zero-Camera-Suite/pull/25), please test and let me know if that resolved your issue. Thanks!
