### ISSUE TITLE
Camera 180 degrees rotation problem.

### ISSUE THREAD

**Issue by 4k3or3et** [CodyTolene/Flipper-Zero-Camera-Suite#57]
Hi All,

when camera is set to be rotated by 180 degrees then when you move camera to the right side, the picture moving is inverted. I think when you set camera to be rotated by 180 degrees, picture should be inverted horizontally.

**Comment by CodyTolene** [comment]
Thank you for your report I will look into this as soon as I can

**Comment by CodyTolene** [comment]
Resolved here:
https://github.com/CodyTolene/Flipper-Zero-Camera-Suite/pull/56

Thanks @4k3or3et!
